name: Deploy Lambda Layer
on:
  # Execute after publish npm so latest packages are installed.
  workflow_run:
    workflows: [NPM Publish]
    types:
      - completed

# on: [pull_request]

jobs:
  layers:
    environment: production
    name: Upload Lambda Layer
    runs-on: ubuntu-latest
    env:
      LAYER_NAME: iguhealth_layer_newprod
      S3_BUCKET: iguhealth-lambda-layers-newprod

    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 21.6.1
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      - name: EnableCorePack
        run: corepack enable

      - name: Install Lambda Deps
        run: cd layers/lambda && npm install @iguhealth/client @iguhealth/artifacts@latest @iguhealth/fhir-patch-building@latest @iguhealth/fhir-pointer@latest @iguhealth/fhir-types@latest @iguhealth/fhir-validation@latest @iguhealth/fhirpath@latest @iguhealth/generated-ops@latest @iguhealth/hl7.fhir.r4.core@latest @iguhealth/meta-value@latest @iguhealth/operation-execution@latest @iguhealth/operation-outcomes@latest

      - name: Create NODEJS DIR
        run: mkdir nodejs

      - name: Move Node modules to dir
        run: mv layers/lambda/node_modules nodejs/node_modules

      - name: Package in Zip
        run: zip -r layer.zip nodejs

      - name: Configure AWS credentials from Github account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::611909812228:role/iguhealth_github_action_user
          aws-region: us-east-1

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws s3 cp layer.zip s3://${S3_BUCKET}/${GITHUB_RUN_ID}.layer.zip

      - name: Publish Layer
        run: |
          aws lambda publish-layer-version --layer-name ${LAYER_NAME} --content S3Bucket=${S3_BUCKET},S3Key=${GITHUB_RUN_ID}.layer.zip --compatible-runtimes nodejs20.x nodejs16.x --description "Iguhealth Layer"
